# SITE CONFIGURATION
title: AvsThiago # your site title
author: Thiago Alves # You :P
description: > # Meta description of Homepage
  An awesome blog where I'll share with you what I'm learning related to Artificial Intelligence, 
  Machine Learning, Deep Learning, Computer Vision and some insights about Python.
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Thiago Alves
  links:
    - https://twitter.com/avsthiago
    - https://www.facebook.com/avsthiago
    - https://www.linkedin.com/in/avsthiago
    - https://plus.google.com/107747883410881429000
    - https://github.com/avsthiago

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Let's learn AI!

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: avsthiago@gmail.com # email for form submission

twitter_username: avsthiago # replace with your_twitter_username or comment to remove link from footer
github_username:  avsthiago # replace with your_github_username or comment to remove link from footer
instagram_username: avsthiago # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: avsthiago # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
