---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
upload_dir: assets/img/posts
public_path: "/assets/img/posts"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
